### ISSUE TITLE
Options are not saved

### ISSUE THREAD

**Issue by greghesp** [claytonjn/SmartThingsPublic#34]
When you setup the SmartApp, select all the devices and click done.  The lamp are saved. 
If you go back into the SmartApp, it looks like the app has not yet been setup, which means when you want to add a new lamp, you need to add all of them again

**Comment by claytonjn** [comment]
Are you referring to Circadian Daylight, or Hue Advanced (Connect)?

**Comment by greghesp** [comment]
Sorry, didn't notice that!
Circadian Daylight

**Comment by claytonjn** [comment]
No problem. It's working for myself and a handful of others I know of, so let's try to figure out what's causing the issue for you. First off, are you on the stable or beta branch?

**Comment by greghesp** [comment]
I'm running 2.6 which i think in the Stable branch

**Comment by claytonjn** [comment]
Yes, that's stable. That was the last version released by Kristopher before he handed the project over to me. Are you using GitHub integration, and if so did you change the repository after I took over the project?

**Comment by greghesp** [comment]
Im in the UK so no GitHub integration unfortunately!  I've just found your 3.1 version, not sure how I found the other but will update. 

EDIT: Updated to 3.1, still experiencing the issue

**Comment by claytonjn** [comment]
Okay, so first thing you should try is installing version 3.1 (latest stable version) or version 4 (latest beta version) from my repository. If you're setting things up for the first time I would suggest going with the beta version for now, because it will probably become the stable version any day now and going from 3->4 will require a complete re-installation.

**Comment by claytonjn** [comment]
Also, are you making sure to copy the code from the RAW view in GitHub?

**Comment by greghesp** [comment]
Yes.  I've selected the dev version 4.  Seems to have fixed the issue

**Comment by claytonjn** [comment]
Alright, I'm going to close this issue but feel free to open another if you have additional issues.
