### ISSUE TITLE
CD not applying to bulb groups

### ISSUE THREAD

**Issue by jtotham** [claytonjn/SmartThingsPublic#41]
I have 9 hue white ambiance bulbs split into 5 groups, all my automations, switches and routines enable and disable these lights by group. 

I can manually change the groups with the sliders and all the bulbs respond as expected but all the groups have the CD enabled but none of them every change colour temp automatically.

Is this a known bug with grouped lights?

**Comment by claytonjn** [comment]
This is not a known bug, I have multiple light groups that work correctly with CD. In fact, SmartThings does not know the difference between a Hue group and an individual light. 

For starters, it sounds like you're using Hue Advanced (Connect) for your Hue bulbs, is that correct?

Do you also have the Circadian Daylight Coordinator and Circadian Daylight SmartApps installed and configured? Hue Advanced (Connect) allows for some individual CD control, but does not include CD functionality, you still need to have CD properly installed and configured.

**Comment by jtotham** [comment]
Totally my bad, I miss-interpreted the DO NOT USE warning in the CD plugin and had removed it. I've added it back in and now my groups are changing as expected.
